- services/pddb/README.md
Fixed 2 minor typos in README.md for PDDB
> Edit minor typos

- tools/pddbdbg.py
Fixed minor typos in comments (I guessed "ts" was "its")
> Fix minor typos

- services/xous-names/src/api.rs
- services/xous-names/src/main.rs
This opcode allows a client to request a connection to the Server, and
will only return if there's an Error or a Connection.
This contains future support for AuthenticationRequests, however those
are not yet implemented.
Signed-off-by: Sean Cross <sean@xobs.io>
> xous-names: add `BlockingConnect` opcode

- services/graphics-server/src/backend/betrusted.rs
When going to sleep, I wanted the screen to be entirely cleared around the "Sleeping" note. This is to avoid having any secrets or sensitive information accidentally linger on the persistent display.
I changed the `suspend` framebuffer operation to clear out any state in the framebuffer just before sleeping. Let me know if you want me to take this in a different direction, or if you have any other feedback. Thanks!
Before:
After:
> During sleep, clear the rest of the screen around the sleep note

- services/ffi-test/src/bindings.rs
1. POSIX compat: `realloc(NULL, size)` is the same as `malloc(size)`.
2. Evict old blocks using `swap_remove` instead of `remove` for const performance.
3. **Critical**: the length of a new block must be set explicitly.
> Fix realloc()

- services/gam/src/bitmap.rs
- services/graphics-server/src/op.rs
- services/modals/src/lib.rs
- services/modals/src/tests.rs
This PR corrects the issue of incorrect rendering of small images and removes unnecessary clones
> fix gam::Tile render RHS

- utralib/build.rs
Use declarative macros and compile-time computations to make feature flags checks more cleaner and future-proof at the cost of introducing some macros.
> utralib: employ macros to simplify features check

- .gitignore
- apps/mtxcli/README.md
- apps/mtxcli/locales/i18n.json
- apps/mtxcli/src/cmds.rs
- apps/mtxcli/src/cmds/get.rs
- apps/mtxcli/src/cmds/help.rs
- apps/mtxcli/src/cmds/set.rs
- apps/mtxcli/src/cmds/status.rs
- apps/mtxcli/src/cmds/unset.rs
/get key -- shows value of key (from the PDDB)
/set key value -- sets value of key (in the PDDB)
/unset key -- removes key (from the PDDB)
/status -- shows status of the connection
Updates mtxcli README
PLEASE review the use of std for PDDB in cmd.rs
> Adds mtxcli commands using the PDDB

- svd2utra/src/generate.rs
Based on #256. Should be merged after it.
> svd2utra: fix clippy lints

- services/gam/src/api.rs
- services/status/src/main.rs
This PR draws a Wi-Fi signal bar with 5 bars (lowest to highest signal), to the right of SSID name.
Signal power is calculated from a lowest of -90dBm to a maximum of -30dBm, by increments of 13dBm.
> feat: wifi signal bar

- libs/mass-storage/usbd_mass_storage/src/msc.rs
For some unknown reason, just adding a second bulk endpoint descriptor makes enumeration fail on essentially all operating systems.
Adding three endpoints is no issue though, but since we want to avoid wasting resources around here, writing 0x42 at the end of the last bulk endpoint... fixes everything: this is a ugly hack, but less ugly than before.
Tested under Linux, Windows, OpenBSD, FreeBSD.
> mass-storage: just use two bulk endpoints

- Cargo.lock
- apps/mtxcli/Cargo.toml
- apps/mtxcli/locales/i18n.json
- apps/mtxcli/src/cmds.rs
- apps/mtxcli/src/cmds/help.rs
- apps/mtxcli/src/cmds/login.rs
- apps/mtxcli/src/cmds/logout.rs
- apps/mtxcli/src/cmds/migrations.rs
- apps/mtxcli/src/cmds/status.rs
- apps/mtxcli/src/cmds/web.rs
Added more predefined scalar messages
Checks WiFi status
Spawns separate thread for client_sync (reading the network) Most all log messages are now INFO (to be shown by default)
Closes #300
Signed-off-by: Tom Marble <tmarble@info9.net>
> mtxcli: chat room updates asynchronously

- kernel/src/arch/hosted/mod.rs
- kernel/src/arch/hosted/process.rs
- kernel/src/services.rs
- kernel/src/syscall.rs
The most recent libstd patch changed the way that process threads were readied. This resulted in inconsistencies in hosted mode where threads weren't properly activated. This should fix those instances.
It is lightly tested, but was shown to work.
> kernel: fix hosted mode

- apps/transientdisk/src/flash_drive.rs
- apps/transientdisk/src/main.rs
A few quality of life improvements, nothing major!
> `transientdisk` cleanup

- services/xous-log/Cargo.toml
- services/xous-log/src/main.rs
- services/xous-log/src/platform/atsama5d2/console.rs
- services/xous-log/src/platform/atsama5d2/debug.rs
- services/xous-log/src/platform/atsama5d2/implementation.rs
- services/xous-log/src/platform/atsama5d2/mod.rs
- services/xous-log/src/platform/hosted/implementation.rs
- services/xous-log/src/platform/hosted/mod.rs
- services/xous-log/src/platform/mod.rs
- services/xous-log/src/platform/precursor/debug.rs
- services/xous-log/src/platform/precursor/implementation.rs
- services/xous-log/src/platform/precursor/mod.rs
- xtask/src/main.rs
This PR also refactors `xous-log` code to allow for easier multiplatform support.
> xous-log: add support for sama5d27

- services/graphics-server/src/backend/betrusted.rs
- services/graphics-server/src/backend/minifb.rs
- services/graphics-server/src/main.rs
> graphics-server: Run `minifb` event loop on main thread

- Cargo.lock
- svd2utra/.gitignore
- svd2utra/Cargo.toml
- svd2utra/src/generate.rs
- svd2utra/src/lib.rs
- svd2utra/src/main.rs
This removes the .gitignore file as the root one manages the files/folders it ignores, removed dependency on pointer sized types and removed an unused dependency.
Also added SPDX license comments at the top of the file.
> svd2utra: improve code

- Cargo.lock
- Cargo.toml
- RELEASE-v0.9.md
- services/net/Cargo.toml
- services/net/src/api.rs
- services/net/src/api/rkyv_enum.rs
- services/net/src/device.rs
- services/net/src/lib.rs
- services/net/src/main.rs
- services/net/src/std_glue.rs
- services/net/src/std_tcplistener.rs
- services/net/src/std_tcpstream.rs
- services/net/src/std_udp.rs
- services/shellchat/Cargo.toml
- services/shellchat/src/nettests.rs
- xous-rs/src/definitions/messages/envelope.rs
- xous-rs/src/definitions/messages/mod.rs
This PR upgrades smoltcp to the current main. This is not meant for release, since the version isn't nailed down, but it's good for CI/testing as smoltcp either gets to the next release, or we pin it to a version.
> Smoltcp port

- apps/mtxchat/Cargo.toml
- libs/chat/src/lib.rs
- libs/tls/README.md
- libs/tls/locales/i18n.json
- libs/tls/src/danger.rs
- libs/tls/src/lib.rs
fix various items - including an alternate response to [#451](https://github.com/betrusted-io/xous-core/pull/451)
> minor fixes across chat components

- libs/tls/src/cmd.rs
- libs/tls/src/lib.rs
- services/net/src/tests.rs
- services/shellchat/src/nettests.rs
> replace TcpStream::connect(&str) with TcpStream::connect((&str, u16))

- emulation/peripherals/BetrustedWatchdog.cs
- kernel/src/arch/riscv/mod.rs
> Minor renode fixes

- kernel/Cargo.toml
- kernel/src/arch/riscv/mod.rs
- kernel/src/arch/riscv/process.rs
- kernel/src/mem.rs
- kernel/src/server.rs
- kernel/src/services.rs
- kernel/src/syscall.rs
This fixes a few potential issues that were discovered in the kernel. One is major, and can result in reading uninitialized memory.
This does not yet solve the intermittent issues I've been seeing, but should probably be pulled in anyway.
> Kernel memory fixes

- services/gam/src/tokens.rs
helps to test things...couldn't do that earlier due to system issues. this actually works now.
> fix comparison on previous PR

- xtask/src/builder.rs
this should throw a hard error now if an app path specified does not exist in hosted mode
(as opposed to starting and only very subtly indicating that an app failed to run)
> check that app paths exist in hosted mode

- apps/manifest.json
- libs/tls/locales/i18n.json
- locales/build.rs
- tools/i18n_helper.py
Tls was missing translations causing compilation issues. I added a function in the i18n_updater.py to fill in any missing translations which have an English message with a stub post fixed by " *EN*". While not ideal, it is nice to be able to quickly fix compilation issues after adding a new language. In a future PR, I'd like to use an LLM to attempt an machine translation of any missing translations or English stubs, but that will require a slight refactor of the i18n_helper first.
> Fix Localization Issues

- publish.py
held in PR to merge shortly after the next merge to save on CI cycles. This script does not impact any of the "live" codebase, it's just a script used to help maintain version pin upgrades on remote packages.
> upgrade the publish script to maintain remote sha2 crate

- Cargo.toml
the crate is patched so @kotval can do dev work on the crate, but we should build from mainline for CI testing for now.
> chore: fix patch pin for curve25519-dalek

- kernel/src/arch/riscv/mem.rs
- kernel/src/syscall.rs
fixup some regressions due to the swap merge
> Fixup swap

- loader/Cargo.toml
this shouldn't be here in main.
> remove debug-print from loader

- loader/src/platform/cramium/cramium.rs
- services/graphics-server/src/backend/cramium.rs
> chore: CI fixes

- Cargo.lock
- kernel/src/io.rs
- services/graphics-server/Cargo.toml
- services/graphics-server/src/backend/minifb.rs
- xtask/src/main.rs
this gives a work around for #538. waiting for a couple days to see if there is a new release on minifb before merging.
> patches for #538

- Cargo.lock
- Cargo.toml
- apps/vault/libraries/crypto/Cargo.toml
- apps/vault/libraries/crypto/src/ecdh.rs
> attempt to remove the last hold-out legacy sha2 dependency

- RELEASE-v0.9.md
- tools/restore.py
Update the restore URL and create a placeholder for new release notes.
> Release bump to 0.9.16

- Cargo.lock
- kernel/src/arch/riscv/mem.rs
- kernel/src/mem.rs
- kernel/src/swap.rs
- loader/Cargo.toml
- loader/src/platform/cramium/cramium.rs
- services/cram-console/Cargo.toml
- services/cram-console/src/cmds.rs
- services/cram-console/src/cmds/mbox.rs
- services/shellchat/src/cmds/test.rs
- services/xous-log/src/platform/cramium/implementation.rs
- services/xous-swapper/src/lib.rs
- services/xous-swapper/src/main.rs
- xtask/src/main.rs
Also includes the ability to allocate contiguous blocks of physical memory for DMA targets.
> Mbox tests & contiguous RAM allocations

- kernel/src/platform/cramium/rand.rs
- libs/cramium-hal/src/sce/trng.rs
- loader/src/platform/cramium/swap.rs
fix a subtle bug in the TRNG's CSPRNG whitener implementation in the loader, and improve docs.
> Trng rework

- tools/updater/precursorupdater/precursorupdater.py
Provide a more descriptive error message when pyusb can't find a backend USB library.
> Improve USB no backend available message

- services/modals/src/lib.rs
- services/shellchat/Cargo.toml
- services/shellchat/src/cmds/usb.rs
Useful for passing data into air-gapped machines with no network connections, but you can plug in a keyboard.
> Nettype - facility to "type" data retrieved from a URL

- rustfmt.toml
this latest change to nightly looks like it's going to wreak havoc on the code base :(
i wish they would stabilize more formatting options, ugh.
> change rustfmt to track changes in nightly

- libs/cramium-hal/src/minigfx.rs
- libs/cramium-hal/src/sh1107.rs
- libs/cramium-hal/src/usb/driver.rs
- libs/xous-bio-bdma/src/bio_tests/dma.rs
- loader/Cargo.toml
- loader/src/asm.rs
- loader/src/platform/cramium.rs
- loader/src/platform/cramium/cramium.rs
- loader/src/platform/cramium/gfx.rs
- loader/src/platform/cramium/swap.rs
- loader/src/platform/cramium/usb/driver.rs
- loader/src/platform/cramium/usb/irq.rs
- loader/src/platform/cramium/usb/mass_storage.rs
- services/cram-console/Cargo.toml
- services/cram-console/src/cmds.rs
- services/cram-console/src/cmds/mbox.rs
- xtask/src/main.rs
Merge MPW changes to avoid branch divergence.
> Mpwevb dev

- libs/cramium-hal/src/board/baosec.rs
- libs/cramium-hal/src/udma/mod.rs
- libs/cramium-hal/src/udma/spim.rs
- services/bao-video/src/main.rs
- services/xous-swapper/Cargo.toml
- services/xous-swapper/src/main.rs
closing up this chapter, we've got some work-arounds and QR decoding is working...acceptably. More improvement is attainable by improving the "fourth corner" extraction.
> Udma debug

- tools/i18n_helper.py
Fixed a couple typos and ran all the commands and fixed the various encoding errors, adding some other error handling.
All the commands seem to work now.
> Fix up i18n_helper.py

- utralib/cramium/core.svd
- utralib/src/generated/cramium_soc.rs
this has come back again due to volatility in the coreuser API
> add updated register profile to include the coreuser block

- apps/hello/src/main.rs
- apps/hidv2/src/main.rs
- apps/mtxcli/src/mtxcli.rs
- apps/repl/src/repl.rs
- apps/transientdisk/src/main.rs
- apps/vault/src/prereqs.rs
- apps/vault/src/ux/framework.rs
- kernel/src/arch/arm/process.rs
- kernel/src/arch/riscv/process.rs
- kernel/src/debug/gdb.rs
- libs/chat/src/ui.rs
- libs/cramium-hal/src/board/baosec.rs
- services/codec/src/backend/tlv320aic3100.rs
- services/cram-console/src/repl.rs
- services/graphics-server/src/backend/minifb.rs
- services/ime-frontend/src/main.rs
- services/llio/src/main.rs
- services/net/src/device.rs
- services/net/src/std_tcplistener.rs
- services/net/src/std_udp.rs
- services/pddb/src/backend/hw.rs
- services/root-keys/src/backups.rs
- services/root-keys/src/lib.rs
- services/shellchat/src/main.rs
- services/xous-names/src/main.rs
- tools/src/bin/create-image.rs
- tools/src/bin/make-renode-boot.rs
- tools/src/utils.rs
- xtask/src/main.rs
needed to get a clean check on gh
> formatting changes due to changes in nightly rust

- services/bao-video/src/main.rs
- services/modals/src/lib.rs
This patch should fix the doc-deps CI item.
> Fix doc-deps issue

- RELEASE-v0.9.md
- services/graphics-server/src/main.rs
Some paths were not fully expanded in alternate targets.
> Fix minor issues in native build targets

- services/graphics-server/src/backend/minifb.rs
API change that was missed in refactoring that CI picked up.
> fix hosted mode build

- libs/cramium-hal/src/board/baosec.rs
this is necessary to meet 50MHz timing on NTO
> fix slew and drive rating for SPI interface

- utralib/cramium/daric.svd
- utralib/src/generated/cramium_soc.rs
based on tape-out RTL
probably some fix-up to do for specific registers that failed to extract correctly due to script errors, but this should get us through the next milestone at least...
> add a closer-to-final NTO SVD file and hw artifact

- Cargo.lock
- libs/cramium-hal/src/board/hosted.rs
- libs/cramium-hal/src/board/mod.rs
- libs/cramium-hal/src/lib.rs
- services/bao-console/Cargo.toml
- services/bao-console/src/cmds/pddb.rs
- services/bao-console/src/main.rs
- services/cramium-emu/src/lib.rs
- services/keystore/src/lib.rs
- services/keystore/src/platform/hosted.rs
- services/pddb/Cargo.toml
- services/pddb/src/api.rs
- services/pddb/src/backend/hosted.rs
- services/pddb/src/backend/hw.rs
- services/pddb/src/backend/pagetable.rs
- services/pddb/src/backend/trngpool.rs
- services/pddb/src/main.rs
Hosted mode PDDB now working with the baosec config.
Let's check CI that we haven't broken anything else in the process of doing this before we move onto the bare iron port.
> Pddb hosted debug

- kernel/Cargo.toml
- kernel/src/mem.rs
- libs/precursor-hal/src/board/precursor.rs
- services/bao-console/Cargo.toml
- services/bao-console/src/main.rs
- services/xous-swapper/Cargo.toml
- services/xous-swapper/src/lib.rs
> Fix hosted mode build targets

- Cargo.lock
- kernel/src/arch/riscv/irq.rs
- kernel/src/platform/cramium/mod.rs
- loader/Cargo.toml
- loader/build.rs
- loader/src/main.rs
- loader/src/phase2.rs
- loader/src/platform/cramium/link-fpga.x
- services/cram-mbox1/Cargo.toml
- services/cram-mbox1/src/main.rs
- utralib/cramium/soc.svd
- utralib/src/generated/cramium_fpga.rs
- xtask/src/main.rs
fixes to enable verilator simulations to run on vexii targets
> Fix verilator

- apps/vault/libraries/cbor/src/writer.rs
- apps/vault/libraries/persistent_store/src/linear.rs
- apps/vault/libraries/persistent_store/src/storage.rs
- apps/vault/src/ctap/hid/mod.rs
- apps/vault/src/env/xous/storage.rs
- imports/getrandom/src/xous.rs
- kernel/src/mem.rs
- libs/cramium-hal/src/usb/driver.rs
- libs/mass-storage/usbd_scsi/src/scsi/enums/version_descriptor.rs
- loader/src/debug.rs
- services/aes/src/soft.rs
- services/cram-hal-service/src/trng.rs
- services/dns/src/api.rs
- services/dns/src/time.rs
- services/gam/src/menu.rs
- services/llio/src/api/i2c_api.rs
- services/modals/src/api.rs
- services/modals/src/lib.rs
- services/net/src/api.rs
- services/net/src/api/tcp.rs
- services/net/src/main.rs
- services/pddb/src/lib.rs
- services/pddb/src/libstd/senres.rs
- services/pddb/src/ux.rs
- services/shellchat/src/cmds/test.rs
- services/spinor/src/api.rs
- services/trng/src/lib.rs
- services/usb-device-xous/src/api.rs
> Fix rustc 1.89

- loader/src/asm.rs
broke precursor target with some cleaning up of the asm stub
> fix asm stub

- baremetal/Cargo.toml
- baremetal/src/platform/cramium/cramium.rs
- baremetal/src/repl.rs
- libs/cramium-hal/src/axp2101.rs
- libs/cramium-hal/src/board/baosec.rs
- libs/cramium-hal/src/sce/trng.rs
- loader/src/platform/cramium/cramium.rs
- services/bao-console/src/cmds/test.rs
Adjust the TRNG setup to match the hardware in NTO.
> Trng tweaks

- baremetal/src/main.rs
- baremetal/src/platform/bao1x/debug.rs
- baremetal/src/platform/bao1x/usb/handlers.rs
Fixup some build errors in baremetal target. More CI targets! more errors!
> Fix baremetal

- Cargo.lock
- bao1x-boot/boot1/Cargo.toml
- bao1x-boot/boot1/src/platform/bao1x/usb/driver.rs
- baremetal/Cargo.toml
- baremetal/src/platform/bao1x/bio.rs
- baremetal/src/platform/bao1x/usb/driver.rs
- baremetal/src/repl.rs
Some minor cleanup around bio/bdma code and test routines
> Bdma noodling
