betrusted-io/xous-core

- kernel/README.md
- loader/README.md
- tools/README.md
Fixes links in sub-directory READMEs to top-level documentation.
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
> Update various README links to top-level documentation

- emulation/renode.svd
Quick fix a build break in ticktimer-server by copying the WDT
from the SoC into the emulator so that it can reference
utra::wdt::WATCHDOG_RESET_CODE .
Signed-off-by: Andrew Shen <Andrew.Y.Shen@jacobs.ucsd.edu>
> Copy WDT into emulator to fix build break

- xous-rs/src/syscall.rs
Fixes a few minor typos in the sycall documentation comments.
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
> Fix server typos in syscall doc comments

- services/graphics-server/src/op.rs
It looks like there is a bug in the quadrant iterator.  For the example related to this ticket, the quadrant iterator is proceeding far enough through the arc of the circle to paint a pixel in the stroke color that is inside the rectangle.  It looks like that's the source of the spurious pixel.  By stopping the iterator one pixel past the bounds of the quadrant region, that part of the arc will not be reached and so that spurious pixel will not be drawn.  There might be a better solution involving further investigation of the quadrant iterator.
> #41: Stop iterator when y exceeds one pixel beyond quadrant bounds.

- README.md
Without these two packages, `cargo xtask run` failed for me on Debian 11 (bullseye).
The version of `cargo` and `rustc` provided by the apt package `rustc` also threw the error mentioned about `feature resolver is required`. With the install script from https://rustup.rs a much newer version was provided, `rustc 1.57.0 (f1edd0429 2021-11-29)`, compared to [`rustc (1.48.0+dfsg1-2`)](https://packages.debian.org/bullseye/rustc) provided by `apt install rustc`.
> Document dependencies on libssl-dev libxkbcommon-dev, newer rustc

- emulation/peripherals/BetrustedEcI2C.cs
- emulation/peripherals/BetrustedSocI2C.cs
- emulation/peripherals/BetrustedWatchdog.cs
- emulation/peripherals/ticktimer.cs
ClockEntry now accepts frequency instead of ratio, making the models a tad simpler.
> Update Renode models with new ClockEntry API

- services/codec/src/backend/hostaudio.rs
these methods were added to tlv320aic3100 and are called from services/codec/src/main.rs
> add drain and can_play stubs to hostaudio backend

- .github/workflows/build.yml
- xtask/src/main.rs
This PR adds a small Github CI action to build hosted mode and real hardware image (Renode image in this case) on any `main` push.
Works fine with 4GB RAM but Github doesn't allow setting an arbitrary amount of memory for CI's, so it must be tested.
> Compile for hosted and real hardware on main push

- .github/workflows/build.yml
- xtask/src/main.rs
This is a corner case in Github CI.
> fix: on non-TTY terminals, if forced, proceed with toolchain download and install

- Cargo.lock
- Cargo.toml
- apps/hello/Cargo.toml
- apps/hello/src/main.rs
- apps/manifest.json
I just got my Precursor yesterday (woohoo!). The first thing I did was write a simple "Hello World" application for it. It helped me to write out the most bare-bones Xous application I could, to understand some of the moving pieces. I thought others might also be able to benefit from a more paired-down example.
It's just a simple "Hello World!" TextView. Here's what it looks like in the simulator:
And on device:
Compile with the following command to run it in the simulator:
```
cargo xtask run hello
```
And to compile the app-image and flash via USB:
```
cargo xtask app-image hello
cargo xtask burn-kernel
```
For posterity's sake: I dug through the `BetrustedKdb` source to learn that the "Home" button on the keyboard is what brings up the main context menu, if that's useful for anyone. …
> Add a basic 'hello world' app example

- buildpush.sh
- imports/riscv-0.5.6/assemble.sh
- imports/riscv-0.5.6/check-blobs.sh
- kernel/assemble.sh
- loader/assemble.sh
- tools/factory_reset.sh
- tools/update_ci.sh
- tools/upload_audiotest.sh
- xous-rs/assemble.sh
Systems like OpenBSD and NixOS have bash in different locations. This
allows the various scripts to be run on those systems.
> Switch to using env to find the path to bash.

- Cargo.lock
- xtask/Cargo.toml
- xtask/src/main.rs
This replaces `curl` with `ureq`. One downside is that we no longer get progress updates for the download because `ureq` doesn't support it.
This also parses the assets JSON file to determine the correct URL to download the zipfile from, rather than guessing the correct one.
> Xtask ureq assets

- services/cb-test-c1/src/main.rs
- services/cb-test-c2/src/main.rs
- services/cb-test-srv/src/main.rs
Looks like the cb-test-xxx services need to call `register_name` with two args vs one.
> Pass register_name two args

- emulation/README.md
https://github.com/renode/renode-infrastructure/tree/master/src/Emulator/Peripherals/Peripherals/SPI/NORFlash doesn't seems to be included in the stable version distributed from https://renode.io/#downloads
> README: add note about renode version

- services/gam/Cargo.toml
- services/gam/src/modal.rs
- services/gam/src/modal/notification.rs
- services/modals/src/api.rs
- services/modals/src/lib.rs
- services/modals/src/main.rs
- services/modals/src/tests.rs
I think a qrcode will be critical for blockchain apps and handy for many others to hand off urls or small text snippets to other devices
note there is a breaking change with an additional parameter in show_notification()
```
pub fn show_notification(&self, notification: &str, as_qrcode: bool) -> Result<(), xous::Error> { ... }
```
> add as_qrcode to Notification modal

- services/graphics-server/Cargo.toml
Update minifb to 0.23, which fixes a serious wayland keyboard issue.
CHANGELOG: https://github.com/emoon/rust_minifb/blob/master/CHANGELOG.md#v023-2022-04-19
> Update minifb to 0.23.0

- xous-ipc/src/buffer.rs
It is more helpful to pass thru the error because "couldn't serialize" does not help the developer to resolve the issue.
> Pass thru buffer serialize Err

- emulation/betrusted.resc
Closes #146. Jtag.cs was misspelled in betrusted.resc
Signed-off-by: Daniel Reusche <code@degregat.net>
> Fix jtag peripheral for emulation of xous-release

- services/modals/Cargo.toml
- services/modals/src/api.rs
- services/modals/src/lib.rs
- services/modals/src/main.rs
- services/modals/src/tests.rs
Support for:
- obtaining the index of the selected radiobutton & checkbox
- adding a Vec<&str> of items
These 2 capabilities will allow the developer to:
```
let choices = vec![t!("choice1", xous::LANG), t!("choice2", xous::LANG), t!("choice3", xous::LANG)];
modals.add_list(&choices);
let choice = modals.get_radiobutton(&self, "choose")
match modals.get_radio_index() {
1 => {}
2 => {}
3 => {}
_ => log::warn!("invalid index"),
}
```
> modal selected index support

- apps/ball/src/ball.rs
- services/gam/src/modal/notification.rs
- services/modals/src/api.rs
- services/modals/src/lib.rs
- services/modals/src/main.rs
- services/modals/src/tests.rs
- services/pddb/src/backend/hw.rs
- services/pddb/src/main.rs
- services/root-keys/src/main.rs
- services/status/src/main.rs
- services/status/src/time.rs
change the notification modal to accept the primary message and an
Option of independent text to display as a qrcode
pub fn show_notification(&self, notification: &str, qrtext:Option<&str>) -> Result<(), xous::Error> {}
> enable notification modal text + qrcode

- services/gam/locales/i18n.json
- services/gam/src/modal/notification.rs
- services/modals/src/api.rs
- expand max text.len to 4096
- throw error on overrun
- simplify qrcode rendering (reduced memory & math)
- correct module size by 1px
> refine qrcode handling

- apps/repl/README.md
The link was relative but the README probably moved since then, I believe it's better to have absolute link.
> Fix link in repl demo

- services/gam/src/modal/textentry.rs
Before this commit the `TextEntryPayloads.content()` method --- which is used by library components to fetch data from the multi-text modal --- would only return payloads with `dirty` set to `true`.
Incidentally, omitted fields also count as not `dirty`, inducing a panic when the `modals` library code iterates through results of that method.
This PR makes `TextEntryPayloads` aware of how many payloads its `content()` method must return, allowing non-`dirty` payloads to be used by e.g. validation functions.
Closes #156.
> fix: clamp TextEntryPayloads content slice to the real amount of fields used in the modal

- services/keyboard/src/main.rs
Don't block BlockingKeyListener if there are pending bytes in the `blocking_queue`. Instead, dequeue the oldest byte and return it immediately.
> don't block if the queue isn't empty

- xtask/src/main.rs
When `cargo xtask` is run, one of the arguments passed to the `kernel` is `sha2:0.9.8`, which is not something produced during the build:
```rust
[ana@architect xous-core]$ cargo xtask run --release
Finished dev [unoptimized + debuginfo] target(s) in 0.11s
Running `target/debug/xtask run --release`
No apps specified, adding default apps...
Building gam status shellchat ime-frontend ime-plugin-shell graphics-server ticktimer-server log-server com xous-names keyboard trng llio susres codec sha2:0.9.8 engine-25519 spinor root-keys jtag net dns pddb modals usb-device-xous ball repl
Command: cargo build --features pddbtest --package gam --package status --package shellchat --package ime-frontend --package ime-plugin-shell --package graphics-server --package ticktimer-server --package …
```
> `cargo xtask run` tries to execute non-existing binary.

- kernel/build.rs
It seems there's a typo in the `build.rs` for the `kernel/` package...
> chore: fix typo in build.rs

- services/gam/src/bitmap.rs
- services/graphics-server/src/api/tile.rs
- services/modals/src/lib.rs
- services/modals/src/tests.rs
These iterators process an image pixel-by-pixel in order to significantly reduce memory requirements over the current batch approach.
- `.to_grey(pixel_type)` converts 3 x `u8` RGB bytes to a single `u8` Grey byte. The iterator state holds only the `PixelType` (1 x byte)
- `.shrink(from_width, to_width)` takes the average of a block of u8 grey pixels to generate a single u8 grey pixel. The iterator state holds only 1 x `f32`, 5 x `usize`, a `vec![u16, to_width]` for performance, and a vec![u16, to_width]` to store the averages: where to_width is the width of the outbound image.
- `.dither(burkes, width)` converts 32 x u8 grey pixels to a u32 bitfield using the Burkes diffusion scheme.  The iterator state holds only 4 x `usize`, 1 x `i16` and a `vec![i16, width + 3]` to store the dither …
> Image processing as Adaptor Iterators

- svd2repl/src/main.rs
As the REPL format comes from [Renode Platform](https://github.com/renode/renode), I believe the word 'Rebide' to be a typo for 'Renode' (given the proximity of the letters on a keyboard).
Let's hope it'll make this tool more prominent in search results.
Signed-off-by: Ludovic LANGE <llange@users.noreply.github.com>
> Fix typo in the tool description : 'Rebide' -> 'Renode'

- apps/vault/libraries/backup/src/lib.rs
Small fix for a thing I should've detected earlier.
> fix(vault): don't panic when reading backup::PayloadType off an empty vec

- Cargo.lock
- apps/vault/libraries/backup/src/lib.rs
- apps/vault/tools/vaultbackup-rs/Cargo.toml
- apps/vault/tools/vaultbackup-rs/README.md
- apps/vault/tools/vaultbackup-rs/src/bitwarden.rs
- apps/vault/tools/vaultbackup-rs/src/main.rs
Allows folks with Bitwarden data to (mostly) import it in Vault, both passwords and TOTPs.
`README.md` has been updated accordingly.
It works like this:
1. acquire a Bitwarden JSON export
2. format it in TOTP and password export with `vaultbackup-rs format bitwarden your-file.json`
3. restore either with `vaultbackup-rs restore {totp, password} bitwarden_to_vault_{totps, passwords}.json`
Seems to be working fine for me, further testing is definitely needed.
> feat(vault): support Bitwarden export formatting for Vault

- Cargo.lock
- apps/vault/libraries/backup/src/lib.rs
- apps/vault/tools/vaultbackup-rs/Cargo.toml
- apps/vault/tools/vaultbackup-rs/README.md
- apps/vault/tools/vaultbackup-rs/build.rs
- apps/vault/tools/vaultbackup-rs/src/authenticator.rs
- apps/vault/tools/vaultbackup-rs/src/main.rs
- apps/vault/tools/vaultbackup-rs/src/otpauth_migration.proto
This helps import TOTP keys from Google Authenticator.  `apps/vault/tools/vaultbackup-rs/README.md` has the short summary:
```
$ zbarcam --raw | tee authenticator-export.txt
$ vaultbackup-rs format authenticator authenticator-export.txt
$ vaultbackup-rs restore totp authenticator_to_vault_totps.json
```
> support importing Google Authenticator TOTP into Vault

- kernel/Cargo.toml
- kernel/src/syscall.rs
- xous-rs/Cargo.toml
- xous-rs/src/syscall.rs
- xtask/src/main.rs
this will help speed up performance profiling as we can resolve the physical address of the performance buffer allocated in RAM and use a USB command to read it out, instead of streaming it over serial.
> add virt_to_phys syscall

- services/root-keys/src/implementation.rs
- services/root-keys/src/main.rs
Fixes corner case when user runs menu command to sign gateware from Renode.
> root-keys: gracefully handle cases where gateware signature is malformed, invalid public key or signature type

- apps/vault/src/actions.rs
- apps/vault/src/storage.rs
- apps/vault/src/totp.rs
- apps/vault/src/ux/framework.rs
- xous-rs/src/arch/hosted/process.rs
Avoid allocations in some cases, for example, when formatting to an I/O buffer. Or when formatting an string on a pre-allocated buffer.
Also implicitly implements `ToString`.
> Implement `Display` instead of `Into<String>`.

- apps/vault/src/ctap/ctap1.rs
- services/com/src/api.rs
- services/content-plugin-api/src/lib.rs
- services/graphics-server/src/api/glyphstyle.rs
- services/graphics-server/src/api/points.rs
- services/graphics-server/src/api/shapes.rs
- services/graphics-server/src/api/styles.rs
- services/graphics-server/src/api/text.rs
- services/ime-plugin-api/src/lib.rs
- services/keyboard/src/api.rs
- services/llio/src/api.rs
- services/llio/src/api/llio_api.rs
- services/root-keys/src/api.rs
- xous-rs/src/arch/hosted/process.rs
- xous-rs/src/arch/riscv/process.rs
- xous-rs/src/arch/test/mod.rs
The guidelines on Rust `std` and `core` crates is to implement `From` instead of `Into` as implementing `From` you get the `Into` implementation too. The other way around doesn't.
> Implement From instead of Into.

- kernel/build.rs
- services/gam/build.rs
- services/kernel-test/build.rs
- xous-rs/build.rs
This allows for a more reliable detection of target_os configuration in build scripts. The target is inconsistent between some architectures, notably armv7a is `armv7a-none-eabi` skipping the `unknown` (the vendor, I guess) part. This happen with some of the unrelated Cortex-M targets present, and others may also be.
Signed-off-by: Jean-Pierre De Jesus DIAZ <me@jeandudey.tech>
> Use CARGO_CFG_TARGET_OS in build scripts.

- svd2utra/src/generate.rs
While implementing utralib generation for one of our chip SVD files I faced some issues with incomplete support of SVD spec but also just bugs. Here are the fixes.
@bunnie pls check if it doesn't break Precursor target code generation.
> Verious svd2utra generator bugfixes

- svd2utra/src/generate.rs
Generating a one huge test for all of the peripherals is simple but if given big enough SVD file, this may even crash the `rustc` with a stack overflow message. Does crash for me.
Instead, generating multiple separate tests e.g. one per peripheral still works well but does not crash the compiler.
> svd2utra: generate smaller compile tests for each peripheral

- loader/src/main.rs
This corrects a subtle bug where the following holds true:
1. There are fewer than 4096 bytes of `.bss`
2. The `.bss` ends on a page boundary
Previously, the loader would copy the contents of the section before `.bss` (usually `.sdata` which contains small data allocations, but oocasionally parts of `.text` as well), then zero out `.bss`, **then zero out the remainder of the page**. If the `.bss` ended on a page boundary, the loader would unintentionally **zero out the entire page**.
This adds a check to avoid zeroing out the entire page if it ends on a page boundary.
> Fix loader when bss ends on a page boundary (and is less than 4096 bytes)

- utralib/build.rs
- xtask/src/builder.rs
This patch relies on build flags in order to prevent spurious rebuilds in utralib. Since each build configuration is now gated behind a feature flag, we can rely on cargo's build management to manage when we need to rebuild things.
Each compilation unit ("crate") gets a fingerprint that's composed of a hash of a bunch of sources including selected feature flags. When changing feature flags, this hash changes, meaning cargo treats the outputs as two separate versions.
For example, selecting `--features renode`, my system builds `utralib-0b7f95b43aed6e06`.
When selecting `--features utralib/precursor-a0912d6`, my system builds `utralib-ef4877bbf43451a5`.
These two outputs exist independently and at the same time -- changing the feature flags will cause Cargo to use one or the other.
Because …
> Fix rebuild logic on utralib

- svd2utra/src/generate.rs
Allows to leverage the `derivedFrom` attribute used in larger SVD files when there are numbers of similar peripherals with the same registers but different name and base address.
> Implement derivedFrom SVD attribute for peripherals

- emulation/peripherals/BetrustedEcI2C.cs
- emulation/peripherals/BetrustedSocI2C.cs
fixes #262 
The change is needed to run with Renode 1.13.2. I didn't dig which exact version the change happened on the Renode side -- a quick search in the release notes showed nothing.
> RemoveClockEntry -> TryRemoveClockEntry

- services/gam/src/contexts.rs
- services/gam/src/layouts/modal.rs
- services/graphics-server/src/api.rs
- services/graphics-server/src/backend/betrusted.rs
- services/graphics-server/src/lib.rs
- services/graphics-server/src/main.rs
- services/pddb/locales/i18n.json
- services/pddb/src/main.rs
- services/shellchat/locales/i18n.json
- services/shellchat/src/main.rs
- services/status/src/main.rs
This commit shows two notifications:
1. as soon as the device boots, a notification greets the user and tells them everything is fine, the device is booting
2. as soon as the user enters (or doesn't) enter the password, a notification tell the user Xous is loading and mounting PDDB
I spent too much time on this but I believe it's a nice UX improvement.
> feat: show boot process notifications for PDDB

- kernel/src/syscall.rs
- xous-rs/src/definitions.rs
- xous-rs/src/syscall.rs
This adds scalar5 support to the kernel. I'm not entirely happy with the kernel implementation, but that can be improved later.
This adds a `return_scalar5()` function. Additionally, `Scalar5` can now be returned from `send_message()`.
> Scalar5 support

- api/xous-api-names/src/api.rs
- services/xous-names/src/main.rs
This patchset adds a nonblocking `TryConnect` API call to the name server. This will be used in places such as libstd where the panic routine will attempt to connect to the graphics server and will omit graphical panics if it is not available.
> Add TryConnect call to xous-names

- apps/vault/libraries/backup/src/lib.rs
- apps/vault/src/vendor_commands.rs
- apps/vault/tools/vaultbackup-rs/README.md
While `vault` supports HOTP codes, `vaultbackup` didn't.
This commit brings it to feature parity.
> fix: support HOTP codes in `vaultbackup`

- api/xous-api-ticktimer/src/api.rs
- kernel/src/debug/shell.rs
- kernel/src/server.rs
- kernel/src/syscall.rs
- services/test-spawn/spawn/src/main.rs
- services/xous-ticktimer/src/main.rs
- xous-rs/src/arch/hosted/mod.rs
- xous-rs/src/arch/test/mod.rs
- xous-rs/src/definitions.rs
- xous-rs/src/definitions/messages/envelope.rs
- xous-rs/src/definitions/messages/mod.rs
- xous-rs/src/syscall.rs
This adds syscall #41: `ReplyAndReceiveNext`.
This syscall will respond to a message and then pull the next message out of the queue. This should improve latency. This was tested on hosted mode and in Renode.
As a demonstration, I've converted `xous-ticktimer` to use the new API.
Note that as part of this, `xous::Result::Message` got renamed to `xous::Result::MessageEnvelope`. This shouldn't affect anything.
> Reply and receive next syscall

- kernel/src/arch/hosted/mod.rs
- kernel/src/syscall.rs
- xous-rs/src/syscall.rs
With the introduction of `ReplyAndReceiveNext`, we now have a new way to return memory to a client.
Unfortunately, the underlying machinery wasn't updated to work with this new call, and as a result memory wasn't properly getting translated between processes.
Implement this so that memory now works.
> Fix ReplyAndReceiveNext for hosted mode

- services/shellchat/src/cmds/pddb_cmd.rs
* Adds a "copy" subcommand to the shellchat pddb command.
* Lists "copy" (and "write") in the help for the pddb command.
> A "copy" subcommand for shellchat pddb

- services/usb-device-xous/src/main_hw.rs
Setting it to zero (default if not set) makes mass-storage work under macOS.
> usb-device-xous: don't set device-wide class on mass-storage

- services/gam/src/lib.rs
- services/shellchat/src/cmds/pddb_cmd.rs
This adds a new subcommand `edit` to shellchat's `pddb` command.  
Executing `pddb edit <key>` will make the Precursor type out the text `pddb write <key> <value>` into the typing area, allowing you to easily edit the value and then press enter to store the new value.
Screenshot example:
> add pddb edit (types pddb write <k> <v>)

- Cargo.lock
- apps/mtxcli/Cargo.toml
- apps/mtxcli/README.md
- apps/mtxcli/locales/i18n.json
- apps/mtxcli/src/cmds.rs
- apps/mtxcli/src/cmds/get.rs
- apps/mtxcli/src/cmds/heap.rs
- apps/mtxcli/src/cmds/help.rs
- apps/mtxcli/src/cmds/login.rs
- apps/mtxcli/src/cmds/logout.rs
- apps/mtxcli/src/cmds/migrations.rs
- apps/mtxcli/src/cmds/migrations/v0_9_11_0120.rs
- apps/mtxcli/src/cmds/set.rs
- apps/mtxcli/src/cmds/status.rs
- apps/mtxcli/src/cmds/unset.rs
- apps/mtxcli/src/cmds/web.rs
- apps/mtxcli/src/mtxcli.rs
_NOTE: Before you UPDATE SOFTWARE_ please run `/get _filter` to find the number of your existing filter. You can set this old filter in case you would like to reproduce the old memory consumption behavior.
Normally on startup a new migration will unset _filter -- causing it to get recreated with a more optimal filter.
Updates the mtxcli README with a troubleshooting section that includes:
```
Prequisites: it is essential that the PDDB is mounted and WiFi is
connected before running mtxcli. You can verify these in Shellchat
with `net ping 1.1.1.1`.
```
Introduces "read only" variables (e.g. __version).
Adds /heap command to mtxcli
Adds migrations framework
* Migration for v0.9.11-0120: update the filter
Delays mtxcli initialization until first user input, because we know:
*  RTC Timer is …
> Issue 287: reduces mtxcli memory consumption

- kernel/src/services.rs
- kernel/src/syscall.rs
This PR adds the ability to track which process and thread currently own the quantum. If a Server responds to a message when it owns the quantum, the message will be queued in the Client and the Server will continue execution.
However, if a Client sends a message to a Server and the Server responds, the Client will resume immediately. This ensures that calls such as ElapsedMs or UnlockMutex don't take longer than they should, while ensuring that Servers are able to weather large numbers of messages.
This seems to work, and I think it will improve responsiveness.
> Give servers their full quantum

- kernel/src/services.rs
- kernel/src/syscall.rs
Reverts betrusted-io/xous-core#314
Causes a regression, system only boots this far now:
```
Betrusted/Precursor Bootloader v0.2.3
Using public key: b2927795649d15737c592b8cecbdc9d6aefe7d61278cb37575470c73c55ed0d0
Using public key: 1c9beae32aeac87507c18094387eff1c74614282affd8152d871352edf3f58bb
Signature check passed
Free stack: 0x00000b34
Jumping to loader...
Mapped UART @ 60001000
Process: map success!
Note: character injection via console UART is enabled.
Allocating IRQ...
Claimed IRQ 3
LOG: my PID is 3
LOG: Creating the reader thread
LOG: Xous Logging Server starting up...
LOG: Server listening on address SID([1937076088, 1735355437, 1919251245, 544367990])
LOG: my PID is 3
LOG: Counter tick: 0
INFO:xous_names: my PID is 4 (services\xous-names\src\main.rs:376)
```
> Revert "Give servers their full quantum"

- kernel/src/services.rs
- kernel/src/syscall.rs
This adds back in the `messages-late-return` patch. There were some missing instances of restoring the thread number, and it's unclear why that wasn't caught in testing.
> kernel: syscall: fix restoring thread id

- Cargo.lock
- kernel/src/main.rs
- kernel/src/services.rs
- loader/src/main.rs
- tools/Cargo.toml
- tools/src/bin/create-image.rs
- tools/src/elf.rs
- tools/src/tags/inie.rs
- tools/src/tags/inif.rs
- tools/src/tags/mod.rs
- tools/src/tags/xkrn.rs
- tools/src/xous_arguments.rs
- xtask/src/builder.rs
- xtask/src/main.rs
- xtask/src/verifier.rs
This patch intends to align all the executable objects (kernel, processes) to pages. It also introduces the skeleton of an IniF, which is basically just IniE with the terms search/replaced for now.
The patch also includes the ability to mark a process as `xip` when you add it to the services list. By default, it is not `xip`, but when adding a single service to the list one can toggle its `xip` flag.
Just before calling create-image, the services list is then split into an IniE and IniF list and passed onto the image creator as such. At the moment IniF is more of a no-op, it just packs it in as an IniE but with a different flag (and the loader wouldn't be able to parse the image either), but it creates a scaffolding for later on handling the `xip` processes differently. The aim is to have …
> WIP: XIP loader support

- kernel/src/main.rs
- kernel/src/services.rs
- loader/src/main.rs
- tools/src/elf.rs
this commit adds the facilities to extract eh_frame[_header] sections and pass it to each process.
A bump is required to `std` to extract the passed parameters.
> fix: #320 adds the eh_frame tags and passes them to each process

- docs/memory.md
- loader/src/main.rs
- loader/src/phase2.rs
The kernel stack previously was located at the same relative offset as all other programs. While this worked, it is poor form.
Move the kernel stack into the kernel memory region (located in the last 4 megabytes of virtual address).
> loader: move the kernel stack to kernel region

- Cargo.lock
- xtask/Cargo.toml
- xtask/src/builder.rs
- xtask/src/main.rs
- xtask/src/utils.rs
As a part of a series of upcoming PRs extending Xous to support ARMv7-A, it extends `xtask` build system with an ARM target and sets a path forward to adding support for multiple targets and architectures. I'm not clear about the best way forward with Xous `libstd` though. It had received ARM support in [our fork](https://github.com/Foundation-Devices/rust) and due to that I've added the code to choose and download a specific `libstd` bundle depending on the target. Probably a better way might be is to include ARM support into the ["default" libstd](https://github.com/betrusted-io/rust) instead, thus keeping a single download URL.
It also adds `arm-tiny` subcommand as an example, but it's not expected to work until ARM support lands in `utralib`, `kernel` and `loader`.
Our effort of …
> xtask: support multiple different targets

- tools/src/elf.rs
I stumbled upon a weird edge case that causes the loader to panic with the following message:
```
panicked at 'init section addresses are not strictly increasing (new virt: 00042870, last virt: 00042874)', loader/src/phase1.rs:222:25
```
And upon checking the allocated ELF section addresses:
```
2    IniE: entrypoint @ 0002e404, loaded from 00001000.  Sections:
Loaded from 00001000 - Section .ARM.exidx      1088 bytes loading into 000100f4..00010534 flags: NONE
Loaded from 00001440 - Section .rodata        12664 bytes loading into 00010534..000136ac flags: NONE
Loaded from 000045b8 - Section .text          61864 bytes loading into 000236ac..00032854 flags: EXECUTE
Loaded from 00013760 - Section .data             32 bytes loading into 00042854..00042874 flags: WRITE
Loaded from 00013780 - …
```
> elf: fix a section alignment edge case

- xous-rs/src/syscall.rs
`rustdoc` was misinterpreting the indentation and thought that those were Rust example code blocks.
> Fix xous-rs documentation tests

- kernel/src/arch/riscv/irq.rs
- kernel/src/debug/gdb.rs
- services/aes/src/vex/aes128.rs
- services/aes/src/vex/aes256.rs
- services/codec/src/main.rs
This is a series of fixes and improvements required to work under Rust 1.69:
* The big fix is that `Codec` was blowing out the stack. It is now heap allocated.
* An issue with gdb was discovered where the debugger wasn't properly entered when a process crashed. It does now.
* A new warning has appeared. This is now fixed.
> Rust 1.69.0 fixes

- services/graphics-server/src/backend/betrusted.rs
- services/graphics-server/src/backend/minifb.rs
- services/graphics-server/src/main.rs
[`minifb::Window::update_with_buffer`][1] needs to be called continuously to pump input events. Fixes massive input latency in hosted mode.
[1]: https://docs.rs/minifb/0.23.0/minifb/struct.Window.html#method.update_with_buffer
> graphics-server: Call `minifb::Window::update_with_buffer` continuously

- services/xous-ticktimer/src/main.rs
- services/xous-ticktimer/src/platform/atsama5d2/implementation.rs
- services/xous-ticktimer/src/platform/hosted/implementation.rs
- services/xous-ticktimer/src/platform/precursor/implementation.rs
This PR allow implementations to override some details about how timer calculates the delays for the next response and fixes the behavior of the SAMA5D2 timer implementation by adding an extra counter to keep track of the time passed.
> ticktimer: fix for ARM to allow multiple clients

- services/graphics-server/src/backend/betrusted.rs
Fixes [image build failure](https://github.com/betrusted-io/xous-core/pull/374#issuecomment-1525990080) after #374.
> graphics-server: convert "never" types in `backend::betrusted::claim_main_thread`

- Cargo.lock
- kernel/Cargo.toml
- services/pddb/Cargo.toml
- services/spinor/Cargo.toml
- services/usb-device-xous/Cargo.toml
- services/usb-test/Cargo.toml
In some places rand 0.8 is already used so this makes it all the same for the rest of the crates in the repository.
> Update rand to 0.8

- kernel/src/arch/riscv/mem.rs
- kernel/src/debug/gdb/multi_thread_base.rs
This improves GDB memory access times by coalescing 2-, 4-, and multi-byte reads and writes. This should improve access times considerably.
This is done through two methods:
1. The TLB is no longer flushed on every byte read or written. The TLB is flushed only when performing a write to a page that was marked readonly, as is the case when patching a running program.
2. Accesses are coalesced. Two-byte aligned accesses are now done in one operation, as are four-byte aligned accesses. Multi-byte reads that are aligned to four-bytes are batched as a sequence of four-byte reads.
This should improve memory access speeds considerably. Would you mind trying this on real hardware?
> Faster gdb memory access

- services/keyboard/src/main.rs
This closes #386 by ignoring any keys over 0xf000
Not sure this is a completely correct logic. Checked with key codes that seem to be injected on Latin, Cyrillic and japanese Kana keyboard on macOS Ventura.
> Fix #386: Ignore key codes over 0xf000 on insert

- kernel/src/arch/arm/mem.rs
- kernel/src/syscall.rs
- xous-rs/src/syscall.rs
This syscall allows services to obtain a physical address from a mapping of a specific process. A particular use case for this is a way for a GUI server to allow client "apps" to allocate a frame buffer and then "register" it by passing FB's virtual address to the GUI server. GUI server is then makes `virt_to_phys_pid` syscall to obtain a physical address of a frame buffer and configures an LCD controller peripheral or a DMA controller to access this physical memory location.
> Add virt_to_phys_pid syscall

- apps/vault/locales/i18n.json
- apps/vault/src/actions.rs
- apps/vault/src/itemcache.rs
- apps/vault/src/main.rs
- apps/vault/src/storage.rs
- apps/vault/src/ux/framework.rs
- services/dns/src/main.rs
- services/net/src/lib.rs
- services/pddb/src/lib.rs
- services/shellchat/src/cmds/net_cmd.rs
This refactors the item cache in `vault` to improve performance by ~100x.
It turns out that sorting is faster than copying, by a couple orders of magnitude.
The original version of the code used a `BTreeMap` to ensure two properties about the item cache:
1. only one entry per key
2. items are in-order after reading from the PDDB, so that they are displayed in alphabetical order when browsing
A `filter` was then applied to the `BTreeMap` to create a view of the data that would include a subset of the PDDB information based on the search string entered. The `filter` would have to copy entries out of the map into a vector because of lifetime issues, and the fact that the structure spans two threads (one thread handling the UX interactions, another thread handling the core logic). 
It turns …
> Refactor item cache

- xous-rs/src/arch/riscv/process.rs
Previously, `ProcessStartup' did not have `repr(C)' above it. This meant that it was using rust layout, which is weird and is not compatible with `_xous_syscall_return_result'.
This should fix issue #381.
> Fix `ProcessStartup'

- services/pddb/src/libstd/mod.rs
- services/pddb/src/main.rs
However, I didn't write this library (and I don't have a test suite for it), so I'm not quite sure if this preserves the invariants on the `fd_mapping()` structure. Needs @xobs' review.
Basically, rust 1.71.0 flags a warning that the `drop` call inside of the `close_key()` method does nothing.
I think the intent was to ensure that the memory for the key inside `fd_mapping()` was de-allocated after the key was closed.
I think the right way to fix it is, should the `close_key` call succeed, simply call `.remove()` on `fd_mapping`.
But I am worried that maybe it was intended that the `fd` should persist for some reason across calls or what not because I don't fully understand the semantics of this library, which is why I am asking for @xobs review.
> Suggested method to preserve intent of `drop` to fix clippy warning

- apps/mtxchat/README.md
- apps/mtxchat/src/lib.rs
- apps/mtxchat/src/listen.rs
- apps/mtxchat/src/web.rs
- libs/tls/Cargo.toml
- libs/tls/src/lib.rs
- libs/tls/src/xtls.rs
Set up tls with `rustls::ClientConnection`,
BUT - on `Error::InvalidCertificate` - then
probe the host for the untrusted certificate chain and prompt the user to perhaps trust one of the certificates in the chain - then try again.
> integrate tls trusted root_store into mtxchat

- apps/mtxchat/locales/i18n.json
- apps/mtxchat/src/lib.rs
- apps/mtxchat/src/listen.rs
- libs/chat/locales/i18n.json
- libs/chat/src/api.rs
- libs/chat/src/lib.rs
- libs/chat/src/main.rs
- libs/chat/src/ui.rs
- services/gam/src/lib.rs
- services/gam/src/main.rs
- services/graphics-server/src/api/text.rs
- services/graphics-server/src/op.rs
- services/graphics-server/src/testing.rs
This is intermediate progress on issue #426.
The animation doesn't work yet, but wanted to clear the overall API with @nworbnhoj before getting stuck in the weeds debugging something that doesn't meet the requirement. 
So, first, this PR implements a simple status bar primitive, it looks a little like this:
The initial status is just that message you see on the top. 
At a high level, the usage for the busy message is something like this:
https://github.com/betrusted-io/xous-core/blob/4142549804b69ce6e0b8722c3dd68cbc72643013/apps/mtxchat/src/lib.rs#L632-L641
What this is supposed to do is change the status message to the argument of `set_busy_state()`, and then start an animation that runs in the background while a message is being sent (in practice it's not happening, but I don't want to …
> WIP: Chat status

- Cargo.lock
- apps/vault/Cargo.toml
- apps/vault/src/env/xous/mod.rs
- apps/vault/src/main.rs
- services/usb-device-xous/Cargo.toml
- services/usb-device-xous/src/lib.rs
- services/usb-device-xous/src/main_hosted.rs
- services/usb-device-xous/src/main_hw.rs
- services/usb-test/Cargo.toml
- services/usb-test/src/main.rs
This PR fixes the `main` branch to track the latest changes in usb-human-interface-device (we were at API rev 0.2.1, this brings it up to 0.4.3).
Note that ... as far as I can tell most of the changes are cosmetic -- method names seem to be renamed to be more "rusty".
Aside from the renamings, the timer requirement is removed from keyboard devices.
@gsora - I'm fine to fork the crate at 0.2.1, but wanted to see what you thought about these changes. If you want me to pull these in prior to forking usbd-human-interface-device, I'm happy to. But I am also equally happy to fork at the older API rev if you see no clear advantage to adopting the changes.
Aside from that, I don't see any earth-changing fixes -- a bunch of dependencies got bumped, maybe they were bumped because security problems …
> RFQ: is it worth it to absorb the lates usbd-human-interface-device changes prior to forking?

- Cargo.toml
- apps/manifest.json
- apps/sigchat/Cargo.toml
- apps/sigchat/README.md
- apps/sigchat/locales/i18n.json
- apps/sigchat/src/account.rs
- apps/sigchat/src/account/service_environment.rs
- apps/sigchat/src/api.rs
- apps/sigchat/src/lib.rs
- apps/sigchat/src/main.rs
- apps/sigchat/src/manager.rs
- apps/sigchat/src/manager/group_permission.rs
- apps/sigchat/src/manager/link_state.rs
- apps/sigchat/src/manager/trust_mode.rs
This is the skeleton of a Signal chat application - **sigchat**
The UI and local storage are provided by the xous chat library.
The structure of the Signal interface is modelled on [signal-cli](https://github.com/AsamK/signal-cli) by AsamK and contributors. `signal-cli` is a command-line interface for `libsignal-service-java`. It supports registering, verifying, sending and receiving messages. This development provides a welcome road-map of the various common transactions between a Signal client and server - see the `signal-cli` [Manual Page](https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc). This road-map is sketched out in `apps/sigchat/src/manager.rs`, but will be subject to refinement as sigchat development progresses.
The Rust implementation of each method stub …
> Sigchat skeleton

- Cargo.lock
- xtask/src/app_manifest.rs
- xtask/src/builder.rs
- xtask/src/main.rs
- xtask/src/utils.rs
- xtask/src/verifier.rs
- xtask/src/versioning.rs
A BinaryFile was previously identified only by its path, thus if a binary file represented an app rather than a service, there was no information that could go in the manifest for the gam. This let's one optionally specify a name for a BinaryFile. 
This may be too subtle, and we can decide on a different api, but I just added an Option<String> for the name in the CrateSpecs::BinaryFile and modified what needed to be modified to support that. Similar to the `name#url` syntax for a prebuilt app from the interwebs, I did a `name:path-to-binary` syntax to represent this, with the option of leaving that off as well. 
Note: I applied rustfmt to the files at the same time. I probably should not have done that so that it is easier to see just the changes. If you'd like me to redo this to fix that …
> Modify xtask to permit named BinaryFile

- libs/xous-pio/src/pio_tests/units.rs
have to slow down the defalut clock rate for the FIFO test in PIO unit test, so we can capture results in simulation
> chore: fix default clock rate for simulation framework

- services/graphics-server/src/wordwrap.rs
there's something....weird....going on in the initializers here and ... something about configurations not being applicable to expressions??
i'm a little confused, but, the original work-around I had to this isuse somehow side-effected things in some way that I didn't expect. this reverts those side effects.
> fix default font settings

- RELEASE-v0.9.md
- services/status/src/main.rs
- services/usb-device-xous/src/api.rs
- services/usb-device-xous/src/lib.rs
- services/usb-device-xous/src/main_hw.rs
This should implement #478.
I have tested that this works with webauthn/FIDO2, but unfortunately all of the U2F test sites that I know of have suffered from bit-rot and have ceased to work due to various security policies that have rolled out over the years.
> Implement #478

- xtask/src/builder.rs
- xtask/src/main.rs
- xtask/src/verifier.rs
fix a build system bug that crept in during the previous big refactor
> Fix remote pkgs

- emulation/peripherals/WF200.cs
- kernel/src/arch/mod.rs
- kernel/src/main.rs
- kernel/src/mem.rs
- kernel/src/services.rs
- kernel/src/syscall.rs
- xous-rs/src/arch/mod.rs
- xous-rs/src/definitions.rs
- xtask/src/builder.rs
- xtask/src/main.rs
- xtask/src/utils.rs
Rust 1.76.0 is the first version that supports unwinding. This is a fairly major change for Xous.
One of the problems is that we apparently cannot build with `panic = "abort"` any more. This will need some more investigation, but for now the easiest approach is to just build everything normally.
Things get a bit funny with the kernel and loader, though. Because we don't want unwinding machinery on these targets, we'll need to build with `riscv32imac-unknown-none-elf` as a target.
This patchset supports this new arrangement. With this patchset, we are able to build under Rust 1.76.0 while we find a better solution for possibly supporting both `panic = "abort"` and `panic = "unwind"`.
> Build kernel and loader using `riscv32imac-unknown-none-elf` -- fixes 1.76.0

- emulation/betrusted.resc
Expose `app_uart` to TCP port 3456 to allow for attaching GDB.
> emulation: expose gdb serial to port 3456

- kernel/src/arch/riscv/process.rs
- kernel/src/mem.rs
- kernel/src/services.rs
DUe to https://github.com/rust-lang/rust/issues/114447 direct access to static mut variables causes a warning which will be turned into an error in the 2024 edition.
The workaround is to use `addr_of!()` and `addr_of_mut!()` macros and then dereference that.
> kernel: use addr_of!() and addr_of_mut!()

- .cargo/config
- Cargo.lock
- Cargo.toml
- services/root-keys/Cargo.toml
- services/root-keys/src/main.rs
- services/shellchat/Cargo.toml
- services/shellchat/src/cmds/engine.rs
- xtask/src/main.rs
This PR complements https://github.com/betrusted-io/curve25519-dalek/pull/2
As a note to self, before merging, the Cargo.toml needs to be pointed to the final github link, instead of a system-local copy.
> Curve25519

- RELEASE-v0.9.md
- services/usb-device-xous/src/main_hw.rs
this allows us to type into hosts that have different keymappings from each other without requiring a reboot.
> check keymap on every call to "type" over USB

- xtask/src/main.rs
This is the branch for working out swap integration into the kernel. A provisional to-do list includes:
> WIP: iron out swap integration in kernel

- Cargo.lock
- tools/Cargo.toml
git tags now returns a 9-digit commit rev instead of 8 in some versions of linux. This causes `u32` parsing of the rev to fail. handle this.
> bump xous-semver rev

- services/com/src/lib.rs
hopefully this gets the CI build warning-free finally...some issues following the jenkins build log because the auto-scroll feature keeps disconnecting today...
> fix a doc warning that slipped through the cracks

- README.md
- RELEASE-v0.9.md
- emulation/peripherals/vexriscv-aes.cs
Newer versions of Renode rename PrivilegeArchitecture to PrivilegedArchitecture. They appear to have tried to work around this by annotating it with `[NameAlias("privilegeArchitecture")]`, however that doesn't change the fact that the actual type itself changed as well.
This incompatible change will cause breakage on older versions of Renode.
This closes #570
> renode: vexriscv: fix CPU on newer Renode versions

- Cargo.lock
- rustfmt.toml
this seems the less disruptive option of 2021 vs 2024.
> Rustfmt to 2024 version

- libs/xous-bio-bdma/Cargo.toml
- libs/xous-bio-bdma/src/bio_tests/arith.rs
- libs/xous-bio-bdma/src/bio_tests/dma.rs
- libs/xous-bio-bdma/src/bio_tests/units.rs
some patches for improved BIO block tests and configs. In particular we're including the single-cycle multiplier so that generated code can be rv32-imc target.
> Biobdma timing

- loader/src/asm.rs
this turns out to be a bad idea because it corrupts systems that have suspend/resume. Revert this commit.
And this is why we have CI.
> revert statics clearing routine

- tools/usb_update.py
the backup flag can be left "hanging around" if a restore of PDDB is aborted. This command allows a user to override that setting in case this is necessary.
> add an option to reset the backup flag

- libs/cramium-hal/src/udma/i2c.rs
this is necessary because the cpu can easily outrun the udma block as the reset is processing, causing the re-initialization to fail.
> modify i2c reset condition to have wait states

- libs/cramium-hal/Cargo.toml
- libs/cramium-hal/src/board/mod.rs
this is for SoC testing with i.e. no peripherals or simulated peripherals in a simulated environment
> add a test target with limited scope

- libs/blitstr2/src/blit.rs
- libs/ux-api/src/minigfx/clip.rs
- libs/ux-api/src/minigfx/handlers.rs
- libs/ux-api/src/service/gfx.rs
- libs/ux-api/src/widgets/modal.rs
- libs/ux-api/src/widgets/slider.rs
- services/bao-console/src/main.rs
- services/bao-console/src/repl.rs
- services/bao-console/src/shell.rs
- services/pddb/src/backend/hw.rs
- services/pddb/src/main.rs
- services/usb-device-xous/src/hid.rs
- xtask/src/main.rs
Various improvements to front end UI aesthetics
- fixed slider spacing
- fixed bug in size checks for draw list creation
- removed "mystery line" on right hand side of screen (this is the dirty bit being applied from precursor targets to the wrong target; checked on renode and the fix seems to not affect legacy systems)
- cleanup some warnings and feature flags
> UI cleanup

- services/cram-hal-service/src/i2c_lib.rs
See issue #659 
Build `main` with `--feature "battery-readout"`. Observe that the values are 0 on console.
`git checkout sam.i2c-fix` and build again. Observe that the values are no longer 0.
> add back in the reading part of `i2c_read`

- kernel/src/arch/riscv/mem.rs
- kernel/src/swap.rs
The double-flush in activate() has a big impact on performance, and I'm pretty sure it only needs to happen after the SATP update not before, at least architecturally. Eliminating the extra flush improves the fast message passing benchmark time by 9%.
> remove some redundant mmu flush commands

- Cargo.lock
- baremetal/src/platform/bao1x/bao1x.rs
- baremetal/src/platform/bao1x/link.x
- libs/bao1x-api/src/lib.rs
- loader/src/main.rs
- loader/src/platform/bao1x/bao1x.rs
- loader/src/platform/bao1x/link.x
- tools/Cargo.toml
- tools/src/bin/copy-object.rs
- tools/src/elf.rs
- xtask/src/builder.rs
- xtask/src/main.rs
@samchin @mammothbane 
I am removing one pain point in the baremetal build process which is having to update the static data initialization with some copypaste code that can change on every build configuration. The original theory was that this didn't change often but as the build has become more featureful that theory went out the door.
This PR incorporates a 256-byte header record on the executables that contains a poke table and other metadata that allows a baremetal system to set up its runtime environment to match what Rust expects. This should hopefully also eliminate some compatibility bugs that could be the cause of the USB serial problems you are having.
> Autostatics
